name: Terraform Release

on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        required: true
        type: string
      AWS_SESSION_TOKEN:
        description: "AWS Session Token"
        required: true
        type: string
      AWS_REGION:
        description: "AWS Region"
        required: false
        default: "us-west-2"
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS Credentials from inputs
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ github.event.inputs.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ github.event.inputs.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ github.event.inputs.AWS_REGION }}" >> $GITHUB_ENV

      - name: Configure AWS credentials (env)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
